// Issue #1405 — hand-authored polarity table for the "Neighbour relations" score.
// The internal key stays `nuisance`, but high now means GOOD: an option that pleases
// the neighbours must raise it, one that annoys them must lower it.
// `effect` is judged from the option's English label and result text (what the
// choice means for the people living next to the mine), NOT from the delta's
// current sign. `alt: true` targets `altConsequence` (the probability-failure
// branch) instead of the main consequence.
//
// Judgement calls on thin evidence (resolved toward the original author's intent):
//  - lawsuit_noise_infractions opt 1 (pay fines only): authorities satisfied -> pleases.
//  - union_motivational_posters opt 2, weather_wind_turbine opt 2: no real benefit to neighbours -> annoys.

export interface PolarityEntry {
  eventId: string;
  option: number;
  alt?: boolean;
  effect: 'pleases' | 'annoys';
}

export const NEIGHBOUR_POLARITY: readonly PolarityEntry[] = [
  { eventId: 'union_karaoke_demand', option: 0, effect: 'annoys' },
  { eventId: 'union_talent_show', option: 0, effect: 'annoys' },
  { eventId: 'union_mascot', option: 2, effect: 'annoys' },
  { eventId: 'union_motivational_posters', option: 2, effect: 'annoys' },
  { eventId: 'union_noise_complaint', option: 0, effect: 'pleases' },
  { eventId: 'union_noise_complaint', option: 2, effect: 'pleases' },
  { eventId: 'union_company_band', option: 0, effect: 'annoys' },
  { eventId: 'union_company_band', option: 2, effect: 'annoys' },
  { eventId: 'union_music_complaint', option: 1, effect: 'annoys' },
  { eventId: 'union_food_trucks', option: 0, effect: 'annoys' },
  { eventId: 'union_golden_hour', option: 1, effect: 'annoys' },
  { eventId: 'union_newsletter', option: 2, effect: 'annoys' },
  { eventId: 'union_anthem', option: 0, effect: 'annoys' },
  { eventId: 'politics_eco_blockade', option: 0, effect: 'pleases' },
  { eventId: 'politics_eco_blockade', option: 1, effect: 'annoys' },
  { eventId: 'politics_reality_tv', option: 0, effect: 'annoys' },
  { eventId: 'politics_reality_tv', option: 1, effect: 'pleases' },
  { eventId: 'politics_reality_tv', option: 2, effect: 'annoys' },
  { eventId: 'politics_mayor_antimine', option: 1, effect: 'pleases' },
  { eventId: 'politics_celebrity', option: 0, effect: 'annoys' },
  { eventId: 'politics_documentary', option: 0, effect: 'annoys' },
  { eventId: 'politics_viral_hashtag', option: 0, effect: 'pleases' },
  { eventId: 'politics_viral_hashtag', option: 1, effect: 'annoys' },
  { eventId: 'politics_viral_hashtag', option: 2, effect: 'pleases' },
  { eventId: 'politics_ev_mandate', option: 0, effect: 'pleases' },
  { eventId: 'politics_ambassador_faint', option: 0, effect: 'pleases' },
  { eventId: 'politics_ambassador_faint', option: 1, effect: 'annoys' },
  { eventId: 'politics_ambassador_faint', option: 2, effect: 'pleases' },
  { eventId: 'politics_ngo_partnership', option: 0, effect: 'pleases' },
  { eventId: 'politics_celebrity_protest', option: 0, effect: 'pleases' },
  { eventId: 'politics_celebrity_protest', option: 1, effect: 'annoys' },
  { eventId: 'politics_celebrity_protest', option: 2, effect: 'pleases' },
  { eventId: 'politics_celebrity_protest', option: 2, alt: true, effect: 'annoys' },
  { eventId: 'politics_heritage_listing', option: 2, effect: 'pleases' },
  { eventId: 'politics_alien_mineral', option: 2, effect: 'annoys' },
  { eventId: 'politics_alien_mineral', option: 2, alt: true, effect: 'annoys' },
  { eventId: 'politics_mine_tourism', option: 0, effect: 'annoys' },
  { eventId: 'politics_mine_tourism', option: 1, effect: 'pleases' },
  { eventId: 'politics_mine_tourism', option: 2, effect: 'annoys' },
  { eventId: 'weather_dust_storm', option: 0, effect: 'pleases' },
  { eventId: 'weather_dust_storm', option: 2, effect: 'annoys' },
  { eventId: 'weather_rainbow_pause', option: 2, effect: 'annoys' },
  { eventId: 'weather_temp_inversion', option: 0, effect: 'pleases' },
  { eventId: 'weather_temp_inversion', option: 1, effect: 'annoys' },
  { eventId: 'weather_temp_inversion', option: 2, effect: 'pleases' },
  { eventId: 'weather_debris_wind', option: 0, effect: 'pleases' },
  { eventId: 'weather_debris_wind', option: 1, effect: 'annoys' },
  { eventId: 'weather_debris_wind', option: 2, effect: 'pleases' },
  { eventId: 'weather_double_rainbow', option: 2, effect: 'annoys' },
  { eventId: 'weather_logo_cloud', option: 2, effect: 'annoys' },
  { eventId: 'weather_tourist_sunrise', option: 0, effect: 'annoys' },
  { eventId: 'weather_tourist_sunrise', option: 2, effect: 'annoys' },
  { eventId: 'weather_wind_turbine', option: 0, effect: 'annoys' },
  { eventId: 'weather_wind_turbine', option: 2, effect: 'annoys' },
  { eventId: 'weather_bird_migration', option: 1, effect: 'annoys' },
  { eventId: 'weather_bird_migration', option: 2, effect: 'annoys' },
  { eventId: 'weather_inland_waterspout', option: 2, effect: 'annoys' },
  { eventId: 'mafia_movie_set', option: 0, effect: 'annoys' },
  { eventId: 'mafia_movie_set', option: 1, effect: 'pleases' },
  { eventId: 'mafia_movie_set', option: 2, effect: 'annoys' },
  { eventId: 'mafia_boss_birthday', option: 0, effect: 'annoys' },
  { eventId: 'mafia_boss_birthday', option: 2, effect: 'annoys' },
  { eventId: 'mafia_family_reunion', option: 0, effect: 'annoys' },
  { eventId: 'mafia_family_reunion', option: 2, effect: 'annoys' },
  { eventId: 'mafia_naming_rights', option: 0, effect: 'annoys' },
  { eventId: 'lawsuit_neighbor_vibrations', option: 0, effect: 'pleases' },
  { eventId: 'lawsuit_neighbor_vibrations', option: 1, effect: 'annoys' },
  { eventId: 'lawsuit_neighbor_vibrations', option: 2, effect: 'pleases' },
  { eventId: 'lawsuit_property_values', option: 0, effect: 'pleases' },
  { eventId: 'lawsuit_property_values', option: 2, effect: 'pleases' },
  { eventId: 'lawsuit_tell_all_book', option: 0, effect: 'annoys' },
  { eventId: 'lawsuit_noise_restraining', option: 0, effect: 'pleases' },
  { eventId: 'lawsuit_noise_restraining', option: 2, effect: 'pleases' },
  { eventId: 'lawsuit_farmer_dust', option: 2, effect: 'pleases' },
  { eventId: 'lawsuit_dust_fashion', option: 0, effect: 'pleases' },
  { eventId: 'lawsuit_dust_fashion', option: 1, effect: 'annoys' },
  { eventId: 'lawsuit_aesthetic_pollution', option: 0, effect: 'pleases' },
  { eventId: 'lawsuit_aesthetic_pollution', option: 1, effect: 'annoys' },
  { eventId: 'lawsuit_aesthetic_pollution', option: 2, effect: 'pleases' },
  { eventId: 'lawsuit_env_cleanup_order', option: 0, effect: 'pleases' },
  { eventId: 'lawsuit_noise_infractions', option: 0, effect: 'pleases' },
  { eventId: 'lawsuit_noise_infractions', option: 1, effect: 'pleases' },
  { eventId: 'lawsuit_school_exams', option: 0, effect: 'pleases' },
  { eventId: 'lawsuit_school_exams', option: 1, effect: 'pleases' },
  { eventId: 'lawsuit_school_exams', option: 2, effect: 'annoys' },
  { eventId: 'lawsuit_village_coalition', option: 0, effect: 'pleases' },
  { eventId: 'lawsuit_village_coalition', option: 1, effect: 'annoys' },
  { eventId: 'lawsuit_celeb_nail', option: 0, effect: 'pleases' },
  { eventId: 'lawsuit_celeb_nail', option: 1, effect: 'annoys' },
  { eventId: 'lawsuit_celeb_nail', option: 2, effect: 'pleases' },
  { eventId: 'lawsuit_celeb_nail', option: 2, alt: true, effect: 'annoys' },
  { eventId: 'lawsuit_mountaineer', option: 1, effect: 'annoys' },
  { eventId: 'lawsuit_mountaineer', option: 2, effect: 'pleases' },
  { eventId: 'lawsuit_explosion_names', option: 0, effect: 'pleases' },
  { eventId: 'lawsuit_explosion_names', option: 1, effect: 'annoys' },
  { eventId: 'lawsuit_explosion_names', option: 2, effect: 'pleases' },
  { eventId: 'lawsuit_peta_goats', option: 0, effect: 'pleases' },
  { eventId: 'lawsuit_peta_goats', option: 1, effect: 'annoys' },
  { eventId: 'lawsuit_peta_goats', option: 2, alt: true, effect: 'annoys' },
  { eventId: 'lawsuit_intl_mining_court', option: 1, effect: 'annoys' },
  { eventId: 'lawsuit_dust_fashion_appeal', option: 0, effect: 'pleases' },
  { eventId: 'lawsuit_dust_fashion_appeal', option: 1, effect: 'annoys' },
  { eventId: 'lawsuit_village_coalition_2', option: 0, effect: 'pleases' },
  { eventId: 'lawsuit_village_coalition_2', option: 1, effect: 'pleases' },
  { eventId: 'lawsuit_village_coalition_2', option: 2, effect: 'pleases' },
  { eventId: 'politics_mayor_wins', option: 2, effect: 'pleases' },
  { eventId: 'politics_diplomatic_incident', option: 0, effect: 'pleases' },
  { eventId: 'politics_diplomatic_incident', option: 1, effect: 'annoys' },
  { eventId: 'politics_diplomatic_incident', option: 2, effect: 'pleases' },
  { eventId: 'weather_lawsuit_debris', option: 0, effect: 'pleases' },
  { eventId: 'weather_lawsuit_debris', option: 1, effect: 'annoys' },
  { eventId: 'weather_lawsuit_debris', option: 1, alt: true, effect: 'pleases' },
  { eventId: 'weather_lawsuit_debris', option: 2, effect: 'pleases' },
];
